basic: Sudoku.h BasicSudoku.cpp
	g++ -std=c++11 -Wall -g -o BasicSudoku BasicSudoku.cpp

best: Sudoku.h BestFirstSearch.h BestFSSudoku.cpp
	g++ -std=c++11 -Wall -g -o BestFSSudoku BestFSSudoku.cpp

breadth: Sudoku.h BreadthFSSudoku.cpp
	g++ -std=c++11 -Wall -g -o BreadthFSSudoku BreadthFSSudoku.cpp

all: basic best breadth